### ISSUE TITLE
RealtimeSubwayLib.swift 파일 클래스별로 파일 나눌까? 말까?

### ISSUE THREAD

**Issue by shoulderMaster** [ProjectInTheClass/GSBN#27]
API 기능별로 파일을 나누는게 더 코드 가독성이 좋을 것 같음

**Comment by LazyRen** [comment]
일단 View Controller 에서 실제 구현 해주는 상황이고 RealtimeSubwayLib에서 클래스랑 구조체 다 들어있는 상황이니까 굳이 안눠도 될 것 같음! 이제 더이상 추가해줄게 없으니까

**Comment by LazyRen** [comment]
7be347f
