### ISSUE TITLE
실시간 지하철 API 연동 - 2

### ISSUE THREAD

**Issue by LazyRen** [ProjectInTheClass/GSBN#8]
request result JSON 파싱

**Comment by shoulderMaster** [comment]
http://data.seoul.go.kr/dataList/datasetView.do?infId=OA-12601&srvType=A&serviceKind=1&currentPageNo=1

일단 이 API에 대한 내용으로만 구현하겠음.
틀이 잡히면 다른 필요한 API에 대해서도 확장 구현.

**Comment by shoulderMaster** [comment]
b8e1764a75664c062e5592f9a72005875a88ba2b
