### ISSUE TITLE
실시간 지하철 연동 - 3

### ISSUE THREAD

**Issue by LazyRen** [ProjectInTheClass/GSBN#9]
fetching한 JSON에서 지하철 위치와 도착예정시간등 필요한 정보 가공하여 저장

json parsing 한 데이터들의 옵셔널 바인딩을 모두 벗겨서 인스턴스로 반환하는 것을 구현해야함.

**Comment by shoulderMaster** [comment]
클래스로 반환할지 구조체로 반환할지 고민되지만 일단 구조체를 택하겠음.

**Comment by shoulderMaster** [comment]
함수형 언어.... fetch한 데이터를 callback 함수 내에서 모든 처리를 해야함.... 하.... 객체로서 반환하는 개념이 없음....
일반적인 객체지향 언어랑 패러다임이 상당히 다름

물론 자바스크립트도 이런 식으로 작동하는거 같았는데 특히 파이썬이랑 비교해보면 상당히 다름...........

**Comment by shoulderMaster** [comment]
내가 생각하는 것은
하나의 큰 클래스 {
  사용자에게 필요한 호선정보
  각 호선에 대한 모든 열차의 위치정보
  위치정보 갱신 함수 () //http request를 보내고 오면 callback함수에서 이 클래스의 위치정보 멤버를 업데이트함. + 테이블 뷰나 커스텀 뷰 업데이트.
  // 하지만 이 작동이 비동기적이여서 갱신한 위치정보를 직접적으로 이용하는건 잘 안될듯, 모든건 callback함수 내에서, 즉 함수형으로 처리해야함
  http 리퀘스트를 보내지 않고 뷰 화면을 기존 정보를 이용하여 computition에 기반하여 업데이트 하는 함수 ()
  추후 필요한거 추가
}

**Comment by shoulderMaster** [comment]
7d8796791dd9844a3d1600e73ef548c35e63c735
